/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opengles_jni_JniRenderer */

#ifndef _Included_com_example_opengles_jni_JniRenderer
#define _Included_com_example_opengles_jni_JniRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opengles_jni_JniRenderer
 * Method:    setGLSLPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_jni_JniRenderer_setGLSLPath
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_opengles_jni_JniRenderer
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_jni_JniRenderer_onSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opengles_jni_JniRenderer
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_jni_JniRenderer_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_opengles_jni_JniRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_jni_JniRenderer_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
